Repository PramdhanniDPB/django-api-ninja, pull requests merged in 2022-10, with the labels that each got.

#1 Create Django Project (1)
  .gitignore
  api_v1/__init__.py
  api_v1/__pycache__/__init__.cpython-310.pyc
  api_v1/__pycache__/views.cpython-310.pyc
  api_v1/admin.py
  api_v1/apps.py
  api_v1/migrations/__init__.py
  api_v1/models.py
  api_v1/routes/__pycache__/retrieve_data.cpython-310.pyc
  api_v1/routes/retrieve_data.py
  api_v1/schema/retrieve_schema.py
  api_v1/tests.py
  api_v1/views.py
  manage.py
  simple_api/__init__.py
  simple_api/__pycache__/__init__.cpython-310.pyc
  simple_api/__pycache__/settings.cpython-310.pyc
  simple_api/__pycache__/urls.cpython-310.pyc
  simple_api/__pycache__/wsgi.cpython-310.pyc
  simple_api/asgi.py
  simple_api/settings.py
  simple_api/urls.py
  simple_api/wsgi.py
Labels: good first issue, hacktoberfest-accepted, Hacktoberfest2022, Hacktoberfest

#2 Add endpoint for retrieve by ID
  .gitignore
  api_v1/routes/retrieve_data.py
Labels: enhancement, good first issue, hacktoberfest-accepted, Hacktoberfest2022, Hacktoberfest

#5 Getting Badges
  README.md
Labels: enhancement, hacktoberfest-accepted, Hacktoberfest2022, Hacktoberfest

#7 update documentation how to use this app
  README.md
Labels: documentation, enhancement, hacktoberfest-accepted, Hacktoberfest2022, Hacktoberfest
